services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rhne_admin_prod
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - NODE_ENV=production
    networks:
      - rhne-network
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.allownonrunning=true"
      - "traefik.http.routers.rhne-admin.rule=Host(`rhne-admin.swiftapp.ch`)"
      - "traefik.http.routers.rhne-admin.entrypoints=websecure"
      - "traefik.http.routers.rhne-admin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.rhne-admin.middlewares=sablier-rhne@file"
      - "traefik.http.services.rhne-admin.loadbalancer.server.port=80"
      - "sablier.enable=true"
      - "sablier.group=rhne"
    deploy:
      resources:
        limits:
          memory: 64M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  rhne-network:
    external: true
  traefik:
    external: true
