export {
  servicesApi,
  useGetServicesQuery,
  useGetServiceByIdQuery,
  useCreateServiceMutation,
  useUpdateServiceMutation,
  useDeleteServiceMutation,
  useGetServiceContactsQuery,
  useCreateServiceContactMutation,
  useUpdateServiceContactMutation,
  useDeleteServiceContactMutation,
  useGetServiceLinksQuery,
  useCreateServiceLinkMutation,
  useUpdateServiceLinkMutation,
  useDeleteServiceLinkMutation,
} from './services.api';
export type {
  Service,
  ServiceContact,
  ServiceLink,
  ServiceFilters,
  CreateServicePayload,
  UpdateServicePayload,
  CreateServiceContactPayload,
  UpdateServiceContactPayload,
  CreateServiceLinkPayload,
  UpdateServiceLinkPayload,
} from './services.types';
